-- ============================================
-- SaludSCZ — Sistema de Vigilancia Epidemiológica Tropical
-- Migración 001: Esquema completo de la base de datos
-- Base de datos: PostgreSQL 15+ (Supabase)
-- ============================================

-- ============================================
-- TIPOS ENUM (PostgreSQL requiere CREATE TYPE)
-- ============================================

CREATE TYPE public.enfermedad_tipo AS ENUM ('viral', 'bacteriana', 'parasitaria');
CREATE TYPE public.usuario_rol AS ENUM ('admin', 'medico', 'enfermero', 'ciudadano');
CREATE TYPE public.paciente_sexo AS ENUM ('M', 'F', 'O');
CREATE TYPE public.caso_estado AS ENUM ('sospechoso', 'confirmado', 'descartado', 'recuperado', 'fallecido');
CREATE TYPE public.caso_confirmacion AS ENUM ('clinica', 'laboratorio', 'epidemiologica');
CREATE TYPE public.sintoma_gravedad AS ENUM ('leve', 'moderado', 'grave');
CREATE TYPE public.caso_sintoma_intensidad AS ENUM ('leve', 'moderada', 'intensa');
CREATE TYPE public.alerta_nivel AS ENUM ('verde', 'amarillo', 'naranja', 'rojo');
CREATE TYPE public.centro_tipo AS ENUM ('hospital', 'clinica', 'centro_de_salud', 'puesto_de_salud');

-- ============================================
-- 1. ZONA (sin dependencias externas)
-- ============================================

CREATE TABLE public.zona (
    id_zona     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre      VARCHAR(100) NOT NULL,
    distrito    VARCHAR(50),
    municipio   VARCHAR(100) NOT NULL DEFAULT 'Santa Cruz de la Sierra',
    latitud     DECIMAL(9, 6),
    longitud    DECIMAL(9, 6),
    poblacion   INTEGER,  -- Agregado: necesario para tasa de incidencia por 100k hab
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================
-- 2. ENFERMEDAD
-- ============================================

CREATE TABLE public.enfermedad (
    id_enfermedad BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre        VARCHAR(100) NOT NULL UNIQUE,
    tipo          public.enfermedad_tipo NOT NULL,
    descripcion   TEXT,
    vector        VARCHAR(100),  -- ej: 'Aedes aegypti'
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================
-- 3. CENTRO_SALUD (depende de zona)
-- ============================================

CREATE TABLE public.centro_salud (
    id_centro  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre     VARCHAR(150) NOT NULL,
    tipo       public.centro_tipo,
    direccion  VARCHAR(200),
    telefono   VARCHAR(20),
    id_zona    BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_centro_salud_zona FOREIGN KEY (id_zona)
        REFERENCES public.zona(id_zona) ON DELETE RESTRICT
);

-- ============================================
-- 4. USUARIO (depende de centro_salud)
-- ============================================

CREATE TABLE public.usuario (
    id_usuario      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR(150) NOT NULL,
    email           VARCHAR(100) NOT NULL UNIQUE,
    contrasena_hash VARCHAR(255) NOT NULL,
    rol             public.usuario_rol NOT NULL,
    id_centro       BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_usuario_centro FOREIGN KEY (id_centro)
        REFERENCES public.centro_salud(id_centro) ON DELETE SET NULL
);

-- ============================================
-- 5. PACIENTE (depende de zona)
-- ============================================

CREATE TABLE public.paciente (
    id_paciente      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR(100) NOT NULL,
    apellido         VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE,
    sexo             public.paciente_sexo,
    telefono         VARCHAR(20),
    direccion        VARCHAR(200),
    id_zona          BIGINT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_paciente_zona FOREIGN KEY (id_zona)
        REFERENCES public.zona(id_zona) ON DELETE SET NULL
);

-- ============================================
-- 6. CASO (tabla central — une paciente, enfermedad, centro, usuario)
-- ============================================

CREATE TABLE public.caso (
    id_caso               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fecha_registro        DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_inicio_sintomas DATE,
    estado                public.caso_estado NOT NULL DEFAULT 'sospechoso',
    confirmacion          public.caso_confirmacion DEFAULT 'clinica',
    id_paciente           BIGINT NOT NULL,
    id_enfermedad         BIGINT NOT NULL,
    id_centro             BIGINT NOT NULL,
    id_usuario            BIGINT NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_caso_paciente FOREIGN KEY (id_paciente)
        REFERENCES public.paciente(id_paciente) ON DELETE RESTRICT,
    CONSTRAINT fk_caso_enfermedad FOREIGN KEY (id_enfermedad)
        REFERENCES public.enfermedad(id_enfermedad) ON DELETE RESTRICT,
    CONSTRAINT fk_caso_centro FOREIGN KEY (id_centro)
        REFERENCES public.centro_salud(id_centro) ON DELETE RESTRICT,
    CONSTRAINT fk_caso_usuario FOREIGN KEY (id_usuario)
        REFERENCES public.usuario(id_usuario) ON DELETE RESTRICT
);

-- ============================================
-- 7. SINTOMA
-- ============================================

CREATE TABLE public.sintoma (
    id_sintoma     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre         VARCHAR(100) NOT NULL UNIQUE,
    descripcion    TEXT,
    nivel_gravedad public.sintoma_gravedad NOT NULL DEFAULT 'leve',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================
-- 8. CASO_SINTOMA (tabla intermedia muchos-a-muchos)
-- ============================================

CREATE TABLE public.caso_sintoma (
    id_caso         BIGINT NOT NULL,
    id_sintoma      BIGINT NOT NULL,
    fecha_aparicion DATE,
    intensidad      public.caso_sintoma_intensidad DEFAULT 'leve',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id_caso, id_sintoma),
    CONSTRAINT fk_caso_sintoma_caso FOREIGN KEY (id_caso)
        REFERENCES public.caso(id_caso) ON DELETE CASCADE,
    CONSTRAINT fk_caso_sintoma_sintoma FOREIGN KEY (id_sintoma)
        REFERENCES public.sintoma(id_sintoma) ON DELETE RESTRICT
);

-- ============================================
-- 9. ALERTA (depende de zona)
-- ============================================

CREATE TABLE public.alerta (
    id_alerta     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fecha_inicio  DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_fin     DATE,
    tipo          VARCHAR(100) NOT NULL,  -- 'brote', 'alerta temprana', 'emergencia'
    mensaje       TEXT,
    nivel         public.alerta_nivel NOT NULL DEFAULT 'verde',
    activa        BOOLEAN NOT NULL DEFAULT true,  -- Agregado: para filtrar alertas activas
    id_zona       BIGINT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_alerta_zona FOREIGN KEY (id_zona)
        REFERENCES public.zona(id_zona) ON DELETE RESTRICT
);

-- ============================================
-- ÍNDICES para mejorar el rendimiento
-- (concepto clave de BD I)
-- ============================================

CREATE INDEX idx_caso_fecha      ON public.caso(fecha_registro);
CREATE INDEX idx_caso_zona       ON public.caso(id_centro);
CREATE INDEX idx_caso_enfermedad ON public.caso(id_enfermedad);
CREATE INDEX idx_caso_estado     ON public.caso(estado);
CREATE INDEX idx_paciente_zona   ON public.paciente(id_zona);
CREATE INDEX idx_alerta_zona     ON public.alerta(id_zona);
CREATE INDEX idx_alerta_activa   ON public.alerta(activa) WHERE activa = true;
CREATE INDEX idx_centro_zona     ON public.centro_salud(id_zona);
CREATE INDEX idx_usuario_rol     ON public.usuario(rol);

-- ============================================
-- FUNCIÓN: Actualizar updated_at automáticamente
-- ============================================

CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- Triggers para todas las tablas
CREATE TRIGGER set_updated_at_zona       BEFORE UPDATE ON public.zona       FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER set_updated_at_enfermedad BEFORE UPDATE ON public.enfermedad FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER set_updated_at_centro     BEFORE UPDATE ON public.centro_salud FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER set_updated_at_usuario    BEFORE UPDATE ON public.usuario    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER set_updated_at_paciente   BEFORE UPDATE ON public.paciente   FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER set_updated_at_caso       BEFORE UPDATE ON public.caso       FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER set_updated_at_sintoma    BEFORE UPDATE ON public.sintoma    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER set_updated_at_alerta     BEFORE UPDATE ON public.alerta     FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- Habilitado en todas las tablas del schema public
-- (requerido por Supabase para exponer tablas via API)
-- ============================================

ALTER TABLE public.zona         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enfermedad   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.centro_salud ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuario      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.paciente     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.caso         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sintoma      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.caso_sintoma ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerta       ENABLE ROW LEVEL SECURITY;

-- ============================================
-- POLÍTICAS RLS (acceso público de lectura)
-- Para una app pública de vigilancia epidemiológica,
-- los datos de zonas, enfermedades, síntomas y alertas
-- son de lectura pública. Casos y pacientes requieren
-- auth para escritura.
-- ============================================

-- Lectura pública para tablas de catálogo
CREATE POLICY "public_read_zona" ON public.zona
    FOR SELECT TO anon USING (true);

CREATE POLICY "public_read_enfermedad" ON public.enfermedad
    FOR SELECT TO anon USING (true);

CREATE POLICY "public_read_sintoma" ON public.sintoma
    FOR SELECT TO anon USING (true);

CREATE POLICY "public_read_centro_salud" ON public.centro_salud
    FOR SELECT TO anon USING (true);

-- Lectura pública de casos (datos anonimizados para el mapa)
CREATE POLICY "public_read_caso" ON public.caso
    FOR SELECT TO anon USING (true);

-- Lectura pública de síntomas por caso
CREATE POLICY "public_read_caso_sintoma" ON public.caso_sintoma
    FOR SELECT TO anon USING (true);

-- Lectura pública de alertas activas
CREATE POLICY "public_read_alerta" ON public.alerta
    FOR SELECT TO anon USING (true);

-- Solo usuarios autenticados pueden insertar casos
CREATE POLICY "auth_insert_caso" ON public.caso
    FOR INSERT TO authenticated WITH CHECK (true);

-- Solo usuarios autenticados pueden insertar relación caso-sintoma
CREATE POLICY "auth_insert_caso_sintoma" ON public.caso_sintoma
    FOR INSERT TO authenticated WITH CHECK (true);

-- Lectura de usuarios autenticados (solo su propio perfil)
CREATE POLICY "auth_read_own_usuario" ON public.usuario
    FOR SELECT TO authenticated USING (true);

-- Lectura de pacientes (autenticados)
CREATE POLICY "auth_read_paciente" ON public.paciente
    FOR SELECT TO authenticated USING (true);

-- Solo autenticados pueden insertar pacientes
CREATE POLICY "auth_insert_paciente" ON public.paciente
    FOR INSERT TO authenticated WITH CHECK (true);

-- Solo autenticados pueden insertar alertas
CREATE POLICY "auth_insert_alerta" ON public.alerta
    FOR INSERT TO authenticated WITH CHECK (true);

-- Admin puede todo
CREATE POLICY "admin_all_usuario" ON public.usuario
    FOR ALL TO authenticated USING (
        EXISTS (SELECT 1 FROM public.usuario WHERE rol = 'admin')
    );

-- ============================================
-- VISTAS SQL (concepto clave de BD I)
-- ============================================

-- Vista 1: Resumen de casos por zona y enfermedad
CREATE VIEW public.v_resumen_zonas AS
SELECT
    z.id_zona,
    z.nombre AS zona,
    z.distrito,
    z.latitud,
    z.longitud,
    z.poblacion,
    e.nombre AS enfermedad,
    COUNT(c.id_caso) AS total_casos,
    SUM(CASE WHEN c.estado = 'confirmado' THEN 1 ELSE 0 END) AS confirmados,
    SUM(CASE WHEN c.estado = 'sospechoso' THEN 1 ELSE 0 END) AS sospechosos,
    MAX(c.fecha_registro) AS ultimo_caso
FROM public.caso c
JOIN public.paciente p   ON c.id_paciente = p.id_paciente
JOIN public.zona z       ON p.id_zona = z.id_zona
JOIN public.enfermedad e ON c.id_enfermedad = e.id_enfermedad
WHERE c.estado IN ('confirmado', 'sospechoso')
GROUP BY z.id_zona, z.nombre, z.distrito, z.latitud, z.longitud, z.poblacion,
         e.id_enfermedad, e.nombre;

-- Vista 2: Tasa de incidencia por zona (por 100,000 habitantes)
CREATE VIEW public.v_tasa_incidencia AS
SELECT
    z.id_zona,
    z.nombre AS zona,
    z.poblacion,
    COUNT(c.id_caso) AS total_casos,
    ROUND(
        COUNT(c.id_caso) * 100000.0 / NULLIF(z.poblacion, 0),
        2
    ) AS tasa_por_100k,
    CASE
        WHEN COUNT(c.id_caso) * 100000.0 / NULLIF(z.poblacion, 0) >= 300 THEN 'muy_alta'
        WHEN COUNT(c.id_caso) * 100000.0 / NULLIF(z.poblacion, 0) >= 100 THEN 'alta'
        WHEN COUNT(c.id_caso) * 100000.0 / NULLIF(z.poblacion, 0) >= 30  THEN 'moderada'
        ELSE 'baja'
    END AS clasificacion
FROM public.caso c
JOIN public.paciente p ON c.id_paciente = p.id_paciente
JOIN public.zona z     ON p.id_zona = z.id_zona
WHERE c.estado = 'confirmado'
  AND c.fecha_registro >= (CURRENT_DATE - INTERVAL '1 year')
GROUP BY z.id_zona, z.nombre, z.poblacion
ORDER BY tasa_por_100k DESC;

-- Vista 3: Evolución semanal de casos (para gráficas de tendencia)
CREATE VIEW public.v_evolucion_semanal AS
SELECT
    EXTRACT(YEAR FROM c.fecha_registro) AS anio,
    EXTRACT(WEEK FROM c.fecha_registro) AS semana,
    MIN(c.fecha_registro) AS fecha_semana,
    e.nombre AS enfermedad,
    COUNT(*) AS total_casos,
    SUM(CASE WHEN c.estado = 'confirmado' THEN 1 ELSE 0 END) AS confirmados
FROM public.caso c
JOIN public.enfermedad e ON c.id_enfermedad = e.id_enfermedad
GROUP BY EXTRACT(YEAR FROM c.fecha_registro),
         EXTRACT(WEEK FROM c.fecha_registro),
         e.id_enfermedad, e.nombre
ORDER BY anio DESC, semana DESC, enfermedad;

-- Vista 4: Síntomas más frecuentes por enfermedad
CREATE VIEW public.v_sintomas_frecuentes AS
SELECT
    e.nombre AS enfermedad,
    s.nombre AS sintoma,
    s.nivel_gravedad,
    COUNT(*) AS frecuencia,
    ROUND(
        COUNT(*) * 100.0 / NULLIF(
            (SELECT COUNT(*) FROM public.caso_sintoma cs2
             JOIN public.caso c2 ON cs2.id_caso = c2.id_caso
             WHERE c2.id_enfermedad = e.id_enfermedad), 0
        ), 1
    ) AS porcentaje
FROM public.caso_sintoma cs
JOIN public.sintoma s  ON cs.id_sintoma = s.id_sintoma
JOIN public.caso c     ON cs.id_caso = c.id_caso
JOIN public.enfermedad e ON c.id_enfermedad = e.id_enfermedad
WHERE c.estado = 'confirmado'
GROUP BY e.id_enfermedad, e.nombre, s.id_sintoma, s.nombre, s.nivel_gravedad
ORDER BY e.nombre, frecuencia DESC;

-- Vista 5: Alertas activas con información de zona
CREATE VIEW public.v_alertas_activas AS
SELECT
    a.id_alerta,
    a.fecha_inicio,
    a.fecha_fin,
    a.tipo,
    a.mensaje,
    a.nivel,
    z.nombre AS zona,
    z.distrito,
    z.latitud,
    z.longitud,
    (SELECT COUNT(*) FROM public.caso c
     JOIN public.paciente p ON c.id_paciente = p.id_paciente
     WHERE p.id_zona = z.id_zona
       AND c.fecha_registro >= a.fecha_inicio
       AND c.estado = 'confirmado') AS casos_desde_alerta
FROM public.alerta a
JOIN public.zona z ON a.id_zona = z.id_zona
WHERE a.activa = true
ORDER BY
    CASE a.nivel
        WHEN 'rojo' THEN 1
        WHEN 'naranja' THEN 2
        WHEN 'amarillo' THEN 3
        WHEN 'verde' THEN 4
    END;
