-- ============================================
-- SaludSCZ — Migracion 005: Reset completo
-- Elimina todo y recrea con datos correctos
-- ============================================

-- ============================================
-- 0. ELIMINAR TODO (orden inverso de dependencias)
-- ============================================

DROP VIEW IF EXISTS public.v_alertas_activas CASCADE;
DROP VIEW IF EXISTS public.v_sintomas_frecuentes CASCADE;
DROP VIEW IF EXISTS public.v_evolucion_semanal CASCADE;
DROP VIEW IF EXISTS public.v_tasa_incidencia CASCADE;
DROP VIEW IF EXISTS public.v_resumen_zonas CASCADE;

DROP TABLE IF EXISTS public.caso_sintoma CASCADE;
DROP TABLE IF EXISTS public.caso CASCADE;
DROP TABLE IF EXISTS public.alerta CASCADE;
DROP TABLE IF EXISTS public.paciente CASCADE;
DROP TABLE IF EXISTS public.usuario CASCADE;
DROP TABLE IF EXISTS public.centro_salud CASCADE;
DROP TABLE IF EXISTS public.sintoma CASCADE;
DROP TABLE IF EXISTS public.enfermedad CASCADE;
DROP TABLE IF EXISTS public.distrito_geo CASCADE;
DROP TABLE IF EXISTS public.zona CASCADE;

DROP FUNCTION IF EXISTS public.update_updated_at() CASCADE;

DROP TYPE IF EXISTS public.enfermedad_tipo CASCADE;
DROP TYPE IF EXISTS public.usuario_rol CASCADE;
DROP TYPE IF EXISTS public.paciente_sexo CASCADE;
DROP TYPE IF EXISTS public.caso_estado CASCADE;
DROP TYPE IF EXISTS public.caso_confirmacion CASCADE;
DROP TYPE IF EXISTS public.sintoma_gravedad CASCADE;
DROP TYPE IF EXISTS public.caso_sintoma_intensidad CASCADE;
DROP TYPE IF EXISTS public.alerta_nivel CASCADE;
DROP TYPE IF EXISTS public.centro_tipo CASCADE;

-- ============================================
-- 1. TIPOS ENUM
-- ============================================

CREATE TYPE public.enfermedad_tipo AS ENUM ('viral', 'bacteriana', 'parasitaria');
CREATE TYPE public.usuario_rol AS ENUM ('admin', 'medico', 'enfermero', 'ciudadano');
CREATE TYPE public.paciente_sexo AS ENUM ('M', 'F', 'O');
CREATE TYPE public.caso_estado AS ENUM ('sospechoso', 'confirmado', 'descartado', 'recuperado', 'fallecido');
CREATE TYPE public.caso_confirmacion AS ENUM ('clinica', 'laboratorio', 'epidemiologica');
CREATE TYPE public.sintoma_gravedad AS ENUM ('leve', 'moderado', 'grave');
CREATE TYPE public.caso_sintoma_intensidad AS ENUM ('leve', 'moderada', 'intensa');
CREATE TYPE public.alerta_nivel AS ENUM ('verde', 'amarillo', 'naranja', 'rojo');
CREATE TYPE public.centro_tipo AS ENUM ('hospital', 'clinica', 'centro_de_salud', 'puesto_de_salud');

-- ============================================
-- 2. TABLAS
-- ============================================

-- 2a. ZONA (con dm_id para distritos oficiales GAMSCZ)
CREATE TABLE public.zona (
    id_zona     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre      VARCHAR(100) NOT NULL,
    distrito    VARCHAR(50),
    municipio   VARCHAR(100) NOT NULL DEFAULT 'Santa Cruz de la Sierra',
    latitud     DECIMAL(9, 6),
    longitud    DECIMAL(9, 6),
    poblacion   INTEGER,
    dm_id       INTEGER,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2b. DISTRITO_GEO (referencia de los 16 distritos oficiales)
CREATE TABLE public.distrito_geo (
    dm_id       INTEGER PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL,
    dm_ext      VARCHAR(100),
    poblacion   INTEGER
);

-- 2c. ENFERMEDAD
CREATE TABLE public.enfermedad (
    id_enfermedad BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre        VARCHAR(100) NOT NULL UNIQUE,
    tipo          public.enfermedad_tipo NOT NULL,
    descripcion   TEXT,
    vector        VARCHAR(100),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2d. CENTRO_SALUD
CREATE TABLE public.centro_salud (
    id_centro  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre     VARCHAR(150) NOT NULL,
    tipo       public.centro_tipo,
    direccion  VARCHAR(200),
    telefono   VARCHAR(20),
    id_zona    BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_centro_salud_zona FOREIGN KEY (id_zona)
        REFERENCES public.zona(id_zona) ON DELETE RESTRICT
);

-- 2e. USUARIO
CREATE TABLE public.usuario (
    id_usuario      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR(150) NOT NULL,
    email           VARCHAR(100) NOT NULL UNIQUE,
    contrasena_hash VARCHAR(255) NOT NULL,
    rol             public.usuario_rol NOT NULL,
    id_centro       BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_usuario_centro FOREIGN KEY (id_centro)
        REFERENCES public.centro_salud(id_centro) ON DELETE SET NULL
);

-- 2f. PACIENTE
CREATE TABLE public.paciente (
    id_paciente      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR(100) NOT NULL,
    apellido         VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE,
    sexo             public.paciente_sexo,
    telefono         VARCHAR(20),
    direccion        VARCHAR(200),
    id_zona          BIGINT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_paciente_zona FOREIGN KEY (id_zona)
        REFERENCES public.zona(id_zona) ON DELETE SET NULL
);

-- 2g. CASO
CREATE TABLE public.caso (
    id_caso               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fecha_registro        DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_inicio_sintomas DATE,
    estado                public.caso_estado NOT NULL DEFAULT 'sospechoso',
    confirmacion          public.caso_confirmacion DEFAULT 'clinica',
    id_paciente           BIGINT NOT NULL,
    id_enfermedad         BIGINT NOT NULL,
    id_centro             BIGINT NOT NULL,
    id_usuario            BIGINT NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_caso_paciente FOREIGN KEY (id_paciente)
        REFERENCES public.paciente(id_paciente) ON DELETE RESTRICT,
    CONSTRAINT fk_caso_enfermedad FOREIGN KEY (id_enfermedad)
        REFERENCES public.enfermedad(id_enfermedad) ON DELETE RESTRICT,
    CONSTRAINT fk_caso_centro FOREIGN KEY (id_centro)
        REFERENCES public.centro_salud(id_centro) ON DELETE RESTRICT,
    CONSTRAINT fk_caso_usuario FOREIGN KEY (id_usuario)
        REFERENCES public.usuario(id_usuario) ON DELETE RESTRICT
);

-- 2h. SINTOMA
CREATE TABLE public.sintoma (
    id_sintoma     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre         VARCHAR(100) NOT NULL UNIQUE,
    descripcion    TEXT,
    nivel_gravedad public.sintoma_gravedad NOT NULL DEFAULT 'leve',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2i. CASO_SINTOMA
CREATE TABLE public.caso_sintoma (
    id_caso         BIGINT NOT NULL,
    id_sintoma      BIGINT NOT NULL,
    fecha_aparicion DATE,
    intensidad      public.caso_sintoma_intensidad DEFAULT 'leve',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id_caso, id_sintoma),
    CONSTRAINT fk_caso_sintoma_caso FOREIGN KEY (id_caso)
        REFERENCES public.caso(id_caso) ON DELETE CASCADE,
    CONSTRAINT fk_caso_sintoma_sintoma FOREIGN KEY (id_sintoma)
        REFERENCES public.sintoma(id_sintoma) ON DELETE RESTRICT
);

-- 2j. ALERTA
CREATE TABLE public.alerta (
    id_alerta     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fecha_inicio  DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_fin     DATE,
    tipo          VARCHAR(100) NOT NULL,
    mensaje       TEXT,
    nivel         public.alerta_nivel NOT NULL DEFAULT 'verde',
    activa        BOOLEAN NOT NULL DEFAULT true,
    id_zona       BIGINT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_alerta_zona FOREIGN KEY (id_zona)
        REFERENCES public.zona(id_zona) ON DELETE RESTRICT
);

-- ============================================
-- 3. INDICES
-- ============================================

CREATE INDEX idx_caso_fecha      ON public.caso(fecha_registro);
CREATE INDEX idx_caso_zona       ON public.caso(id_centro);
CREATE INDEX idx_caso_enfermedad ON public.caso(id_enfermedad);
CREATE INDEX idx_caso_estado     ON public.caso(estado);
CREATE INDEX idx_paciente_zona   ON public.paciente(id_zona);
CREATE INDEX idx_alerta_zona     ON public.alerta(id_zona);
CREATE INDEX idx_alerta_activa   ON public.alerta(activa) WHERE activa = true;
CREATE INDEX idx_centro_zona     ON public.centro_salud(id_zona);
CREATE INDEX idx_usuario_rol     ON public.usuario(rol);

-- ============================================
-- 4. FUNCION Y TRIGGERS
-- ============================================

CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER set_updated_at_zona       BEFORE UPDATE ON public.zona       FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER set_updated_at_enfermedad BEFORE UPDATE ON public.enfermedad FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER set_updated_at_centro     BEFORE UPDATE ON public.centro_salud FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER set_updated_at_usuario    BEFORE UPDATE ON public.usuario    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER set_updated_at_paciente   BEFORE UPDATE ON public.paciente   FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER set_updated_at_caso       BEFORE UPDATE ON public.caso       FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER set_updated_at_sintoma    BEFORE UPDATE ON public.sintoma    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER set_updated_at_alerta     BEFORE UPDATE ON public.alerta     FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ============================================
-- 5. RLS
-- ============================================

ALTER TABLE public.zona         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enfermedad   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.centro_salud ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuario      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.paciente     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.caso         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sintoma      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.caso_sintoma ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerta       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.distrito_geo ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public_read_zona" ON public.zona FOR SELECT TO anon USING (true);
CREATE POLICY "public_read_enfermedad" ON public.enfermedad FOR SELECT TO anon USING (true);
CREATE POLICY "public_read_sintoma" ON public.sintoma FOR SELECT TO anon USING (true);
CREATE POLICY "public_read_centro_salud" ON public.centro_salud FOR SELECT TO anon USING (true);
CREATE POLICY "public_read_caso" ON public.caso FOR SELECT TO anon USING (true);
CREATE POLICY "public_read_caso_sintoma" ON public.caso_sintoma FOR SELECT TO anon USING (true);
CREATE POLICY "public_read_alerta" ON public.alerta FOR SELECT TO anon USING (true);
CREATE POLICY "public_read_distrito_geo" ON public.distrito_geo FOR SELECT TO anon USING (true);
CREATE POLICY "auth_insert_caso" ON public.caso FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_insert_caso_sintoma" ON public.caso_sintoma FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_read_own_usuario" ON public.usuario FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_read_paciente" ON public.paciente FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_insert_paciente" ON public.paciente FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_insert_alerta" ON public.alerta FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "admin_all_usuario" ON public.usuario FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM public.usuario WHERE rol = 'admin')
);

-- ============================================
-- 6. VISTAS
-- ============================================

CREATE VIEW public.v_resumen_zonas AS
SELECT
    z.id_zona, z.nombre AS zona, z.distrito, z.latitud, z.longitud, z.poblacion,
    e.nombre AS enfermedad,
    COUNT(c.id_caso) AS total_casos,
    SUM(CASE WHEN c.estado = 'confirmado' THEN 1 ELSE 0 END) AS confirmados,
    SUM(CASE WHEN c.estado = 'sospechoso' THEN 1 ELSE 0 END) AS sospechosos,
    MAX(c.fecha_registro) AS ultimo_caso
FROM public.caso c
JOIN public.paciente p   ON c.id_paciente = p.id_paciente
JOIN public.zona z       ON p.id_zona = z.id_zona
JOIN public.enfermedad e ON c.id_enfermedad = e.id_enfermedad
WHERE c.estado IN ('confirmado', 'sospechoso')
GROUP BY z.id_zona, z.nombre, z.distrito, z.latitud, z.longitud, z.poblacion,
         e.id_enfermedad, e.nombre;

CREATE VIEW public.v_tasa_incidencia AS
SELECT
    z.id_zona, z.nombre AS zona, z.poblacion,
    COUNT(c.id_caso) AS total_casos,
    ROUND(COUNT(c.id_caso) * 100000.0 / NULLIF(z.poblacion, 0), 2) AS tasa_por_100k,
    CASE
        WHEN COUNT(c.id_caso) * 100000.0 / NULLIF(z.poblacion, 0) >= 300 THEN 'muy_alta'
        WHEN COUNT(c.id_caso) * 100000.0 / NULLIF(z.poblacion, 0) >= 100 THEN 'alta'
        WHEN COUNT(c.id_caso) * 100000.0 / NULLIF(z.poblacion, 0) >= 30  THEN 'moderada'
        ELSE 'baja'
    END AS clasificacion
FROM public.caso c
JOIN public.paciente p ON c.id_paciente = p.id_paciente
JOIN public.zona z     ON p.id_zona = z.id_zona
WHERE c.estado = 'confirmado'
  AND c.fecha_registro >= (CURRENT_DATE - INTERVAL '1 year')
GROUP BY z.id_zona, z.nombre, z.poblacion
ORDER BY tasa_por_100k DESC;

CREATE VIEW public.v_evolucion_semanal AS
SELECT
    EXTRACT(YEAR FROM c.fecha_registro) AS anio,
    EXTRACT(WEEK FROM c.fecha_registro) AS semana,
    MIN(c.fecha_registro) AS fecha_semana,
    e.nombre AS enfermedad,
    COUNT(*) AS total_casos,
    SUM(CASE WHEN c.estado = 'confirmado' THEN 1 ELSE 0 END) AS confirmados
FROM public.caso c
JOIN public.enfermedad e ON c.id_enfermedad = e.id_enfermedad
GROUP BY EXTRACT(YEAR FROM c.fecha_registro),
         EXTRACT(WEEK FROM c.fecha_registro),
         e.id_enfermedad, e.nombre
ORDER BY anio DESC, semana DESC, enfermedad;

CREATE VIEW public.v_sintomas_frecuentes AS
SELECT
    e.nombre AS enfermedad, s.nombre AS sintoma, s.nivel_gravedad,
    COUNT(*) AS frecuencia,
    ROUND(COUNT(*) * 100.0 / NULLIF(
        (SELECT COUNT(*) FROM public.caso_sintoma cs2
         JOIN public.caso c2 ON cs2.id_caso = c2.id_caso
         WHERE c2.id_enfermedad = e.id_enfermedad), 0
    ), 1) AS porcentaje
FROM public.caso_sintoma cs
JOIN public.sintoma s    ON cs.id_sintoma = s.id_sintoma
JOIN public.caso c       ON cs.id_caso = c.id_caso
JOIN public.enfermedad e ON c.id_enfermedad = e.id_enfermedad
WHERE c.estado = 'confirmado'
GROUP BY e.id_enfermedad, e.nombre, s.id_sintoma, s.nombre, s.nivel_gravedad
ORDER BY e.nombre, frecuencia DESC;

CREATE VIEW public.v_alertas_activas AS
SELECT
    a.id_alerta, a.fecha_inicio, a.fecha_fin, a.tipo, a.mensaje, a.nivel,
    z.nombre AS zona, z.distrito, z.latitud, z.longitud,
    (SELECT COUNT(*) FROM public.caso c
     JOIN public.paciente p ON c.id_paciente = p.id_paciente
     WHERE p.id_zona = z.id_zona
       AND c.fecha_registro >= a.fecha_inicio
       AND c.estado = 'confirmado') AS casos_desde_alerta
FROM public.alerta a
JOIN public.zona z ON a.id_zona = z.id_zona
WHERE a.activa = true
ORDER BY CASE a.nivel
    WHEN 'rojo' THEN 1 WHEN 'naranja' THEN 2
    WHEN 'amarillo' THEN 3 WHEN 'verde' THEN 4
END;

-- ============================================
-- 7. SEED DATA
-- ============================================

-- 7a. 16 distritos oficiales GAMSCZ
INSERT INTO public.distrito_geo (dm_id, nombre, dm_ext) VALUES
(1, 'Piraí', NULL), (2, 'Norte Interno', NULL), (3, 'Estación Argentina', NULL),
(4, 'El Pari', NULL), (5, 'Norte', NULL), (6, 'Pampa de la Isla', NULL),
(7, 'Villa Primero de Mayo', NULL), (8, 'Ciudadela Andrés Ibáñez', NULL),
(9, 'Palmasola/Sur', NULL), (10, 'Bajío del Oriente', NULL),
(11, 'Centro', NULL), (12, 'Nuevo Palmar', NULL), (13, 'El Palmar', NULL),
(14, 'Paurito', 'Paurito'), (15, 'Montero Hoyos', 'Montero Hoyos'),
(16, 'Distrito Industrial', 'Distrito Industrial');

-- 7b. 7 zonas verificadas
INSERT INTO public.zona (nombre, distrito, municipio, latitud, longitud, poblacion, dm_id) VALUES
('Centro',            '11', 'Santa Cruz de la Sierra', -17.7833, -63.1821, 120000, 11),
('Equipetrol',        '1',  'Santa Cruz de la Sierra', -17.7646, -63.1959, 85000,  1),
('Urbarí',            '4',  'Santa Cruz de la Sierra', -17.7700, -63.1900, 65000,  4),
('Villa Fátima',      '4',  'Santa Cruz de la Sierra', -17.7500, -63.1600, 95000,  4),
('Palmasola',         '9',  'Santa Cruz de la Sierra', -17.8739, -63.1825, 70000,  9),
('Plan 3000',         '8',  'Santa Cruz de la Sierra', -17.8518, -63.1169, 180000, 8),
('Villa 1ro de Mayo', '7',  'Santa Cruz de la Sierra', -17.7931, -63.1332, 60000,  7);

-- 7c. Enfermedades
INSERT INTO public.enfermedad (nombre, tipo, descripcion, vector) VALUES
('Dengue',      'viral',       'Enfermedad viral febril aguda transmitida por mosquitos Aedes.', 'Aedes aegypti'),
('Chikungunya', 'viral',       'Enfermedad viral transmitida por mosquitos. Fiebre alta y dolor articular severo.', 'Aedes albopictus'),
('Zika',        'viral',       'Enfermedad viral leve en adultos, riesgo de microcefalia en fetos.', 'Aedes aegypti'),
('Leishmaniasis','parasitaria','Enfermedad parasitaria transmitida por mosca de arena.', 'Lutzomyia longipalpis'),
('Malaria',     'parasitaria', 'Enfermedad parasitaria transmitida por mosquito Anopheles.', 'Anopheles darlingi');

-- 7d. Sintomas
INSERT INTO public.sintoma (nombre, descripcion, nivel_gravedad) VALUES
('Fiebre',                'Temperatura corporal superior a 38C',                           'moderado'),
('Cefalea',               'Dolor de cabeza intenso, frontal',                              'leve'),
('Malestar general',      'Sensacion de indisposicion y fatiga',                           'leve'),
('Nauseas',               'Sensacion de asco con o sin vómito',                           'leve'),
('Vomito',                'Expulsion del contenido gastrico por la boca',                  'moderado'),
('Dolor retroocular',     'Dolor detras de los ojos al moverlos',                         'moderado'),
('Dolor articular',       'Dolor en articulaciones (artralgia)',                           'moderado'),
('Dolor muscular',        'Dolor en musculos (mialgia)',                                   'leve'),
('Exantema cutaneo',      'Erupcion cutanea maculopapular',                               'leve'),
('Petecias',              'Manchas rojas en piel por sangrado subcutaneo',                'grave'),
('Hemorragia nasal',      'Sangrado por nariz (epistaxis)',                                'grave'),
('Hemorragia gingival',   'Sangrado de encias',                                            'grave'),
('Dolor abdominal',       'Dolor en la parte baja del abdomen',                           'moderado'),
('Hepatomegalia',         'Aumento del tamano del higado palpable',                       'grave'),
('Derrame pleural',       'Acumulacion de liquido en la cavidad toracica',                'grave'),
('Hemoconcentracion',     'Aumento de concentracion de hemoglobina por deshidratacion',   'grave'),
('Leucopenia',            'Disminucion de globulos blancos en sangre',                    'moderado'),
('Trombocitopenia',       'Disminucion de plaquetas en sangre',                           'grave'),
('Artritis severa',       'Inflamacion articular intensa y persistente',                  'grave'),
('Rigidez matutina',      'Dificultad para mover articulaciones al despertar',            'moderado'),
('Conjuntivitis',         'Inflamacion de la membrana conjuntiva del ojo',               'leve'),
('Fotofobia',             'Sensibilidad anormal a la luz',                                 'leve'),
('Conjuntivitis no purulenta', 'Inflamacion ocular sin pus',                              'leve'),
('Prurito',               'Picazon en piel',                                               'leve'),
('Dolor de espalda',      'Dolor en la zona lumbar',                                       'leve'),
('Ulcera cutanea',        'Herida abierta en piel con bordes elevados',                   'grave'),
('Nodulos subcutaneos',   'Bultos bajo la piel',                                           'moderado'),
('Fiebre irregular',      'Fiebre que oscila intermitentemente',                           'moderado'),
('Esplenomegalia',        'Aumento del tamano del bazo',                                   'grave'),
('Perdida de peso',       'Baja de peso involuntaria',                                     'moderado'),
('Escalofrios',           'Sensacion de frio intenso con temblor',                         'moderado'),
('Sudoracion profusa',    'Sudoracion excesiva despues del escalofrio',                    'leve'),
('Anemia',                'Palidez y debilidad por disminucion de globulos rojos',        'grave'),
('Hepatoesplenomegalia',  'Aumento de higado y bazo simultaneamente',                     'grave'),
('Hemoglobinuria',        'Orina oscura por hemolisis',                                    'grave');

-- 7e. Centros de salud
INSERT INTO public.centro_salud (nombre, tipo, direccion, telefono, id_zona) VALUES
('Hospital Santa Cruz',           'hospital',        'Av. Irala esq. Canoto',      '(591-3) 336-2400', (SELECT id_zona FROM public.zona WHERE nombre = 'Centro')),
('Hospital Japones',              'hospital',        'Av. Burgos',                  '(591-3) 344-5555', (SELECT id_zona FROM public.zona WHERE nombre = 'Equipetrol')),
('Hospital Municipal de Ninos',   'hospital',        'Av. Busch y 3er anillo',     '(591-3) 335-2121', (SELECT id_zona FROM public.zona WHERE nombre = 'Villa 1ro de Mayo')),
('Centro de Salud Centro',        'centro_de_salud', 'Plaza 24 de Septiembre',     '(591-3) 332-1111', (SELECT id_zona FROM public.zona WHERE nombre = 'Centro')),
('Centro de Salud Equipetrol',    'centro_de_salud', 'Barrio Equipetrol',          '(591-3) 334-5678', (SELECT id_zona FROM public.zona WHERE nombre = 'Equipetrol')),
('Centro de Salud Villa Fatima',  'centro_de_salud', 'Barrio Villa Fatima',        '(591-3) 346-1234', (SELECT id_zona FROM public.zona WHERE nombre = 'Villa Fátima')),
('Centro de Salud Plan 3000',     'centro_de_salud', 'Av. Grigota',                '(591-3) 358-9876', (SELECT id_zona FROM public.zona WHERE nombre = 'Plan 3000')),
('Centro de Salud Palmasola',     'centro_de_salud', 'Barrio Palmasola',           '(591-3) 345-4321', (SELECT id_zona FROM public.zona WHERE nombre = 'Palmasola')),
('Clinica Foianini',              'clinica',         'Av. Irala',                  '(591-3) 333-3333', (SELECT id_zona FROM public.zona WHERE nombre = 'Centro')),
('Clinica Alemana',               'clinica',         'Av. Busch',                  '(591-3) 336-6666', (SELECT id_zona FROM public.zona WHERE nombre = 'Equipetrol')),
('Puesto de Salud Urbari',        'puesto_de_salud', 'Barrio Urbari',              '(591-3) 337-8888', (SELECT id_zona FROM public.zona WHERE nombre = 'Urbarí'));

-- 7f. Usuarios
INSERT INTO public.usuario (nombre, email, contrasena_hash, rol, id_centro) VALUES
('Dr. Carlos Mendoza',   'carlos.mendoza@saludscz.bo',   '$2b$10$hashed_password_admin',   'admin',    (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Hospital Santa Cruz')),
('Dra. Ana Garcia',      'ana.garcia@saludscz.bo',       '$2b$10$hashed_password_medico1', 'medico',   (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Hospital Santa Cruz')),
('Dr. Luis Fernandez',   'luis.fernandez@saludscz.bo',   '$2b$10$hashed_password_medico2', 'medico',   (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000')),
('Enf. Maria Lopez',     'maria.lopez@saludscz.bo',      '$2b$10$hashed_password_enf1',    'enfermero',(SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000')),
('Ciudadano Juan Perez', 'juan.perez@ciudadano.bo',      '$2b$10$hashed_password_ciud1',   'ciudadano', NULL);

-- 7g. Pacientes
INSERT INTO public.paciente (nombre, apellido, fecha_nacimiento, sexo, telefono, direccion, id_zona) VALUES
('Paciente', 'HIST-001', '1985-03-15', 'M', NULL, 'Centro',            (SELECT id_zona FROM public.zona WHERE nombre = 'Centro')),
('Paciente', 'HIST-002', '1990-07-22', 'F', NULL, 'Equipetrol',        (SELECT id_zona FROM public.zona WHERE nombre = 'Equipetrol')),
('Paciente', 'HIST-003', '1978-11-08', 'M', NULL, 'Urbari',            (SELECT id_zona FROM public.zona WHERE nombre = 'Urbarí')),
('Paciente', 'HIST-004', '1995-01-30', 'F', NULL, 'Villa Fatima',      (SELECT id_zona FROM public.zona WHERE nombre = 'Villa Fátima')),
('Paciente', 'HIST-005', '1982-06-12', 'M', NULL, 'Plan 3000',         (SELECT id_zona FROM public.zona WHERE nombre = 'Plan 3000')),
('Paciente', 'HIST-006', '1988-09-05', 'F', NULL, 'Palmasola',         (SELECT id_zona FROM public.zona WHERE nombre = 'Palmasola')),
('Paciente', 'HIST-007', '1975-04-18', 'M', NULL, 'Plan 3000',         (SELECT id_zona FROM public.zona WHERE nombre = 'Plan 3000')),
('Paciente', 'HIST-008', '1992-12-25', 'F', NULL, 'Villa 1ro de Mayo', (SELECT id_zona FROM public.zona WHERE nombre = 'Villa 1ro de Mayo')),
('Paciente', 'HIST-009', '1980-08-03', 'M', NULL, 'Centro',            (SELECT id_zona FROM public.zona WHERE nombre = 'Centro')),
('Paciente', 'HIST-010', '1997-02-14', 'F', NULL, 'Villa Fatima',      (SELECT id_zona FROM public.zona WHERE nombre = 'Villa Fátima')),
('Paciente', 'HIST-011', '1983-05-27', 'M', NULL, 'Plan 3000',         (SELECT id_zona FROM public.zona WHERE nombre = 'Plan 3000')),
('Paciente', 'HIST-012', '1991-10-09', 'F', NULL, 'Equipetrol',        (SELECT id_zona FROM public.zona WHERE nombre = 'Equipetrol')),
('Paciente', 'HIST-013', '1976-07-16', 'M', NULL, 'Urbari',            (SELECT id_zona FROM public.zona WHERE nombre = 'Urbarí')),
('Paciente', 'HIST-014', '1994-03-21', 'F', NULL, 'Plan 3000',         (SELECT id_zona FROM public.zona WHERE nombre = 'Plan 3000')),
('Paciente', 'HIST-015', '1987-11-30', 'M', NULL, 'Palmasola',         (SELECT id_zona FROM public.zona WHERE nombre = 'Palmasola')),
('Paciente', 'HIST-016', '1989-04-08', 'F', NULL, 'Centro',            (SELECT id_zona FROM public.zona WHERE nombre = 'Centro')),
('Paciente', 'HIST-017', '1981-08-19', 'M', NULL, 'Plan 3000',         (SELECT id_zona FROM public.zona WHERE nombre = 'Plan 3000')),
('Paciente', 'HIST-018', '1993-06-02', 'F', NULL, 'Villa 1ro de Mayo', (SELECT id_zona FROM public.zona WHERE nombre = 'Villa 1ro de Mayo')),
('Paciente', 'HIST-019', '1979-12-11', 'M', NULL, 'Villa Fatima',      (SELECT id_zona FROM public.zona WHERE nombre = 'Villa Fátima')),
('Paciente', 'HIST-020', '1996-09-28', 'F', NULL, 'Plan 3000',         (SELECT id_zona FROM public.zona WHERE nombre = 'Plan 3000'));

-- 7h. Casos de Dengue 2024-2025
INSERT INTO public.caso (fecha_registro, fecha_inicio_sintomas, estado, confirmacion, id_paciente, id_enfermedad, id_centro, id_usuario) VALUES
('2024-01-08', '2024-01-05', 'confirmado', 'laboratorio',  1,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-01-12', '2024-01-10', 'confirmado', 'clinica',      2,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Equipetrol'),  (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-01-15', '2024-01-13', 'sospechoso', 'clinica',      3,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Puesto de Salud Urbari'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-01-20', '2024-01-18', 'confirmado', 'laboratorio',  5,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-01-22', '2024-01-20', 'confirmado', 'clinica',      7,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-01-25', '2024-01-23', 'sospechoso', 'clinica',      5,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'maria.lopez@saludscz.bo')),
('2024-02-01', '2024-01-29', 'confirmado', 'laboratorio',  1,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-02-03', '2024-02-01', 'confirmado', 'clinica',      4,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Villa Fatima'),(SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-02-05', '2024-02-03', 'confirmado', 'laboratorio',  6,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-02-07', '2024-02-05', 'confirmado', 'clinica',      7,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-02-08', '2024-02-06', 'confirmado', 'laboratorio',  5,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-02-10', '2024-02-08', 'confirmado', 'clinica',      12, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Equipetrol'),  (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-02-12', '2024-02-10', 'confirmado', 'laboratorio',  13, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Puesto de Salud Urbari'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-02-14', '2024-02-12', 'confirmado', 'clinica',      14, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-02-15', '2024-02-13', 'confirmado', 'laboratorio',  8,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-02-17', '2024-02-15', 'confirmado', 'clinica',      17, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-02-19', '2024-02-17', 'confirmado', 'laboratorio',  18, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-02-20', '2024-02-18', 'confirmado', 'clinica',      15, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-02-22', '2024-02-20', 'confirmado', 'laboratorio',  20, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-02-24', '2024-02-22', 'confirmado', 'clinica',      1,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Centro'),      (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-02-26', '2024-02-24', 'confirmado', 'laboratorio',  5,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-02-28', '2024-02-26', 'confirmado', 'clinica',      7,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'maria.lopez@saludscz.bo')),
('2024-03-01', '2024-02-27', 'confirmado', 'laboratorio',  5,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-03-03', '2024-03-01', 'confirmado', 'clinica',      14, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-03-05', '2024-03-03', 'confirmado', 'laboratorio',  17, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-03-07', '2024-03-05', 'confirmado', 'clinica',      2,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Equipetrol'),  (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-03-09', '2024-03-07', 'confirmado', 'laboratorio',  6,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-03-11', '2024-03-09', 'confirmado', 'clinica',      12, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Equipetrol'),  (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-03-13', '2024-03-11', 'confirmado', 'laboratorio',  3,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Puesto de Salud Urbari'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-03-15', '2024-03-13', 'confirmado', 'clinica',      6,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-03-17', '2024-03-15', 'confirmado', 'laboratorio',  7,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-03-19', '2024-03-17', 'confirmado', 'clinica',      13, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Puesto de Salud Urbari'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-03-21', '2024-03-19', 'confirmado', 'laboratorio',  8,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-03-23', '2024-03-21', 'confirmado', 'clinica',      15, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-03-25', '2024-03-23', 'confirmado', 'laboratorio',  20, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-03-27', '2024-03-25', 'confirmado', 'clinica',      1,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Centro'),      (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-03-29', '2024-03-27', 'confirmado', 'laboratorio',  4,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Villa Fatima'),(SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-04-02', '2024-03-30', 'confirmado', 'clinica',      5,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-04-05', '2024-04-03', 'confirmado', 'laboratorio',  7,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'maria.lopez@saludscz.bo')),
('2024-04-08', '2024-04-06', 'confirmado', 'clinica',      5,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-04-12', '2024-04-10', 'sospechoso', 'clinica',      14, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-04-18', '2024-04-16', 'confirmado', 'clinica',      17, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-05-15', '2024-05-13', 'descartado', 'laboratorio',  1,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Centro'),      (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-06-20', '2024-06-18', 'sospechoso', 'clinica',      2,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Equipetrol'),  (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-07-10', '2024-07-08', 'descartado', 'laboratorio',  3,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Puesto de Salud Urbari'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-09-15', '2024-09-13', 'confirmado', 'clinica',      4,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Villa Fatima'),(SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-10-01', '2024-09-29', 'confirmado', 'laboratorio',  5,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-10-15', '2024-10-13', 'confirmado', 'clinica',      6,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-11-01', '2024-10-30', 'confirmado', 'laboratorio',  7,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-11-15', '2024-11-13', 'confirmado', 'clinica',      8,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'maria.lopez@saludscz.bo')),
('2024-12-01', '2024-11-29', 'confirmado', 'laboratorio',  15, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-12-15', '2024-12-13', 'confirmado', 'clinica',      20, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2025-01-10', '2025-01-08', 'confirmado', 'laboratorio',  1,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Centro'),      (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2025-01-20', '2025-01-18', 'confirmado', 'clinica',      5,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2025-02-01', '2025-01-30', 'confirmado', 'laboratorio',  12, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Equipetrol'),  (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2025-02-10', '2025-02-08', 'confirmado', 'clinica',      13, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Puesto de Salud Urbari'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2025-02-20', '2025-02-18', 'confirmado', 'laboratorio',  4,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Villa Fatima'),(SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2025-03-01', '2025-02-27', 'confirmado', 'clinica',      14, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2025-03-10', '2025-03-08', 'confirmado', 'laboratorio',  8,  1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2025-03-20', '2025-03-18', 'confirmado', 'clinica',      17, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2025-04-01', '2025-03-30', 'confirmado', 'laboratorio',  18, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2025-04-10', '2025-04-08', 'confirmado', 'clinica',      15, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2025-04-20', '2025-04-18', 'sospechoso', 'clinica',      20, 1, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo'));

-- 7i. Casos de Chikungunya
INSERT INTO public.caso (fecha_registro, fecha_inicio_sintomas, estado, confirmacion, id_paciente, id_enfermedad, id_centro, id_usuario) VALUES
('2024-02-10', '2024-02-08', 'confirmado', 'laboratorio',  1,  2, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-02-25', '2024-02-23', 'confirmado', 'clinica',      2,  2, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Equipetrol'),  (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-03-05', '2024-03-03', 'confirmado', 'laboratorio',  3,  2, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Puesto de Salud Urbari'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-03-15', '2024-03-13', 'sospechoso', 'clinica',      4,  2, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Villa Fatima'),(SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-03-25', '2024-03-23', 'confirmado', 'laboratorio',  5,  2, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-04-05', '2024-04-03', 'confirmado', 'clinica',      6,  2, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-04-15', '2024-04-13', 'confirmado', 'laboratorio',  7,  2, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-04-25', '2024-04-23', 'sospechoso', 'clinica',      8,  2, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'maria.lopez@saludscz.bo')),
('2025-02-15', '2025-02-13', 'confirmado', 'laboratorio',  15, 2, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2025-03-01', '2025-02-27', 'confirmado', 'clinica',      20, 2, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo'));

-- 7j. Casos de Zika
INSERT INTO public.caso (fecha_registro, fecha_inicio_sintomas, estado, confirmacion, id_paciente, id_enfermedad, id_centro, id_usuario) VALUES
('2024-03-10', '2024-03-08', 'confirmado', 'laboratorio',  1,  3, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Centro'),      (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-03-20', '2024-03-18', 'confirmado', 'clinica',      2,  3, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Equipetrol'),  (SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2024-04-01', '2024-03-30', 'sospechoso', 'clinica',      3,  3, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Puesto de Salud Urbari'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-04-10', '2024-04-08', 'confirmado', 'laboratorio',  4,  3, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Villa Fatima'),(SELECT id_usuario FROM public.usuario WHERE email = 'ana.garcia@saludscz.bo')),
('2025-03-05', '2025-03-03', 'confirmado', 'clinica',      5,  3, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo'));

-- 7k. Casos de Leishmaniasis
INSERT INTO public.caso (fecha_registro, fecha_inicio_sintomas, estado, confirmacion, id_paciente, id_enfermedad, id_centro, id_usuario) VALUES
('2024-06-15', '2024-05-01', 'confirmado', 'laboratorio',  6,  4, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-08-20', '2024-07-15', 'confirmado', 'laboratorio',  7,  4, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-11-10', '2024-10-01', 'confirmado', 'laboratorio',  15, 4, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2025-02-20', '2025-01-15', 'confirmado', 'laboratorio',  17, 4, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Plan 3000'),     (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo'));

-- 7l. Casos de Malaria
INSERT INTO public.caso (fecha_registro, fecha_inicio_sintomas, estado, confirmacion, id_paciente, id_enfermedad, id_centro, id_usuario) VALUES
('2024-05-10', '2024-05-08', 'confirmado', 'laboratorio',  6,  5, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-06-25', '2024-06-23', 'confirmado', 'laboratorio',  7,  5, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-08-05', '2024-08-03', 'confirmado', 'laboratorio',  15, 5, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-09-15', '2024-09-13', 'confirmado', 'laboratorio',  6,  5, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2024-11-20', '2024-11-18', 'confirmado', 'laboratorio',  15, 5, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2025-01-05', '2025-01-03', 'confirmado', 'laboratorio',  6,  5, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo')),
('2025-03-15', '2025-03-13', 'confirmado', 'laboratorio',  15, 5, (SELECT id_centro FROM public.centro_salud WHERE nombre = 'Centro de Salud Palmasola'),  (SELECT id_usuario FROM public.usuario WHERE email = 'luis.fernandez@saludscz.bo'));

-- 7m. Sintomas por caso
INSERT INTO public.caso_sintoma (id_caso, id_sintoma, fecha_aparicion, intensidad) VALUES
(1, 1, '2024-01-05', 'intensa'),  (1, 2, '2024-01-05', 'moderada'), (1, 6, '2024-01-06', 'intensa'), (1, 8, '2024-01-06', 'moderada'), (1, 7, '2024-01-07', 'leve'),
(2, 1, '2024-01-10', 'intensa'),  (2, 2, '2024-01-10', 'moderada'), (2, 6, '2024-01-11', 'intensa'), (2, 8, '2024-01-11', 'moderada'),
(5, 1, '2024-01-18', 'intensa'),  (5, 2, '2024-01-18', 'moderada'), (5, 6, '2024-01-19', 'intensa'), (5, 8, '2024-01-19', 'moderada'), (5, 7, '2024-01-20', 'leve'), (5, 9, '2024-01-20', 'leve'),
(7, 1, '2024-02-01', 'intensa'),  (7, 2, '2024-02-01', 'moderada'), (7, 6, '2024-02-02', 'intensa'), (7, 8, '2024-02-02', 'moderada'), (7, 7, '2024-02-03', 'moderada'), (7, 5, '2024-02-03', 'leve'),
(8, 1, '2024-02-01', 'intensa'),  (8, 2, '2024-02-01', 'moderada'), (8, 6, '2024-02-02', 'intensa'), (8, 8, '2024-02-02', 'moderada'),
(11, 1, '2024-02-06', 'intensa'), (11, 2, '2024-02-06', 'moderada'), (11, 6, '2024-02-07', 'intensa'), (11, 8, '2024-02-07', 'moderada'), (11, 7, '2024-02-08', 'leve'), (11, 10, '2024-02-08', 'leve'),
(12, 1, '2024-02-10', 'intensa'), (12, 2, '2024-02-10', 'moderada'), (12, 6, '2024-02-11', 'intensa'), (12, 8, '2024-02-11', 'moderada'),
(61, 1, '2024-02-08', 'intensa'), (61, 7, '2024-02-09', 'intensa'), (61, 20, '2024-02-10', 'intensa'), (61, 8, '2024-02-09', 'moderada'),
(62, 1, '2024-02-23', 'intensa'), (62, 7, '2024-02-24', 'intensa'), (62, 20, '2024-02-25', 'intensa'), (62, 8, '2024-02-24', 'moderada'),
(66, 1, '2024-03-08', 'leve'),    (66, 9, '2024-03-09', 'moderada'), (66, 23, '2024-03-09', 'leve'), (66, 25, '2024-03-10', 'leve'),
(67, 1, '2024-03-18', 'leve'),    (67, 9, '2024-03-19', 'moderada'), (67, 23, '2024-03-19', 'leve'),
(72, 1, '2024-05-08', 'intensa'), (72, 31, '2024-05-08', 'intensa'), (72, 32, '2024-05-09', 'moderada'), (72, 33, '2024-05-15', 'moderada'),
(73, 1, '2024-06-23', 'intensa'), (73, 31, '2024-06-23', 'intensa'), (73, 32, '2024-06-24', 'moderada'), (73, 33, '2024-06-30', 'moderada');

-- 7n. Alertas
INSERT INTO public.alerta (fecha_inicio, fecha_fin, tipo, mensaje, nivel, activa, id_zona) VALUES
('2024-02-01', NULL, 'brote', 'Brote de dengue activo en Plan 3000. 12 casos confirmados en las ultimas 2 semanas.', 'rojo', true,
    (SELECT id_zona FROM public.zona WHERE nombre = 'Plan 3000')),
('2024-02-10', NULL, 'alerta temprana', 'Incremento de casos sospechosos de dengue en Villa Fatima. 5 casos en la ultima semana.', 'naranja', true,
    (SELECT id_zona FROM public.zona WHERE nombre = 'Villa Fátima')),
('2024-02-15', NULL, 'alerta temprana', 'Circulacion viral detectada en distrito Centro.', 'amarillo', true,
    (SELECT id_zona FROM public.zona WHERE nombre = 'Centro')),
('2024-02-20', NULL, 'monitoreo', 'Situacion estable en Equipetrol. Sin incremento significativo de casos.', 'verde', true,
    (SELECT id_zona FROM public.zona WHERE nombre = 'Equipetrol')),
('2024-01-15', '2024-01-30', 'alerta temprana', 'Alerta inicial en Plan 3000 por primeros casos de temporada.', 'amarillo', false,
    (SELECT id_zona FROM public.zona WHERE nombre = 'Plan 3000')),
('2024-03-01', '2024-04-15', 'emergencia', 'Emergencia epidemiologica por pico historico de dengue en Plan 3000.', 'rojo', false,
    (SELECT id_zona FROM public.zona WHERE nombre = 'Plan 3000'));
