-- ============================================
-- SaludSCZ — Migración 008: Mejoras Profesionales
-- Bitácora de Auditoría, Alertas Automáticas, Canal Endémico
-- ============================================

-- ============================================
-- 1. BITÁCORA DE AUDITORÍA MÉDICA
-- ============================================

CREATE TABLE IF NOT EXISTS public.bitacora_auditoria (
    id_bitacora    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tabla_afectada VARCHAR(100) NOT NULL,
    operacion      VARCHAR(20) NOT NULL,
    id_registro    BIGINT NOT NULL,
    usuario_email  VARCHAR(150),
    datos_anteriores JSONB,
    datos_nuevos   JSONB,
    fecha          TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.bitacora_auditoria ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public_read_bitacora" ON public.bitacora_auditoria FOR SELECT TO public USING (true);
CREATE POLICY "auth_insert_bitacora" ON public.bitacora_auditoria FOR INSERT TO public WITH CHECK (true);

-- Trigger genérico de auditoría para tabla caso
CREATE OR REPLACE FUNCTION public.audit_caso_changes()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO public.bitacora_auditoria (tabla_afectada, operacion, id_registro, usuario_email, datos_nuevos)
        VALUES ('caso', 'INSERT', NEW.id_caso, current_setting('request.jwt.claims', true)::json->>'email', to_jsonb(NEW));
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO public.bitacora_auditoria (tabla_afectada, operacion, id_registro, usuario_email, datos_anteriores, datos_nuevos)
        VALUES ('caso', 'UPDATE', NEW.id_caso, current_setting('request.jwt.claims', true)::json->>'email', to_jsonb(OLD), to_jsonb(NEW));
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO public.bitacora_auditoria (tabla_afectada, operacion, id_registro, usuario_email, datos_anteriores)
        VALUES ('caso', 'DELETE', OLD.id_caso, current_setting('request.jwt.claims', true)::json->>'email', to_jsonb(OLD));
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_audit_caso ON public.caso;
CREATE TRIGGER trg_audit_caso
    AFTER INSERT OR UPDATE OR DELETE ON public.caso
    FOR EACH ROW EXECUTE FUNCTION public.audit_caso_changes();

-- ============================================
-- 2. ALERTAS AUTOMÁTICAS POR UMBRAL EPIDÉMICO
-- ============================================

CREATE OR REPLACE FUNCTION public.evaluar_umbral_alerta()
RETURNS TRIGGER AS $$
DECLARE
    v_id_zona BIGINT;
    v_casos_recientes INT;
    v_poblacion INT;
    v_tasa_ataque NUMERIC;
    v_alerta_existente BOOLEAN;
BEGIN
    -- Obtener zona del paciente del caso insertado
    SELECT p.id_zona INTO v_id_zona
    FROM public.paciente p WHERE p.id_paciente = NEW.id_paciente;

    IF v_id_zona IS NULL THEN RETURN NEW; END IF;

    -- Obtener población
    SELECT poblacion INTO v_poblacion FROM public.zona WHERE id_zona = v_id_zona;
    IF v_poblacion IS NULL OR v_poblacion = 0 THEN RETURN NEW; END IF;

    -- Contar casos confirmados en últimas 2 semanas
    SELECT COUNT(*) INTO v_casos_recientes
    FROM public.caso c
    JOIN public.paciente p ON c.id_paciente = p.id_paciente
    WHERE p.id_zona = v_id_zona
      AND c.estado = 'confirmado'
      AND c.fecha_registro >= (CURRENT_DATE - INTERVAL '14 days');

    v_tasa_ataque := (v_casos_recientes * 100000.0) / v_poblacion;

    -- Verificar si ya hay alerta activa en esa zona
    SELECT EXISTS (
        SELECT 1 FROM public.alerta
        WHERE id_zona = v_id_zona AND activa = true
          AND fecha_inicio >= (CURRENT_DATE - INTERVAL '14 days')
    ) INTO v_alerta_existente;

    IF NOT v_alerta_existente THEN
        IF v_tasa_ataque >= 300.0 THEN
            INSERT INTO public.alerta (fecha_inicio, tipo, mensaje, nivel, activa, id_zona)
            VALUES (CURRENT_DATE, 'brote',
                'ALERTA AUTOMÁTICA: Tasa de ataque crítica (' || ROUND(v_tasa_ataque, 1) || '/100k). ' || v_casos_recientes || ' casos en 14 días.',
                'rojo', true, v_id_zona);
        ELSIF v_tasa_ataque >= 100.0 THEN
            INSERT INTO public.alerta (fecha_inicio, tipo, mensaje, nivel, activa, id_zona)
            VALUES (CURRENT_DATE, 'alerta temprana',
                'ALERTA AUTOMÁTICA: Tasa elevada (' || ROUND(v_tasa_ataque, 1) || '/100k). ' || v_casos_recientes || ' casos en 14 días.',
                'naranja', true, v_id_zona);
        ELSIF v_tasa_ataque >= 30.0 THEN
            INSERT INTO public.alerta (fecha_inicio, tipo, mensaje, nivel, activa, id_zona)
            VALUES (CURRENT_DATE, 'monitoreo',
                'ALERTA AUTOMÁTICA: Incremento moderado (' || ROUND(v_tasa_ataque, 1) || '/100k). ' || v_casos_recientes || ' casos en 14 días.',
                'amarillo', true, v_id_zona);
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_evaluar_alerta ON public.caso;
CREATE TRIGGER trg_evaluar_alerta
    AFTER INSERT ON public.caso
    FOR EACH ROW
    WHEN (NEW.estado = 'confirmado')
    EXECUTE FUNCTION public.evaluar_umbral_alerta();

-- ============================================
-- 3. VISTA PARA CANAL ENDÉMICO
-- Calcula percentiles históricos por semana epidemiológica
-- ============================================

CREATE OR REPLACE VIEW public.v_canal_endemico AS
WITH casos_semanales AS (
    SELECT
        EXTRACT(WEEK FROM c.fecha_registro)::INT AS semana_epi,
        EXTRACT(YEAR FROM c.fecha_registro)::INT AS anio,
        e.nombre AS enfermedad,
        COUNT(*) AS total
    FROM public.caso c
    JOIN public.enfermedad e ON c.id_enfermedad = e.id_enfermedad
    WHERE c.estado = 'confirmado'
    GROUP BY semana_epi, anio, e.nombre
),
stats AS (
    SELECT
        semana_epi,
        enfermedad,
        PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY total) AS p25,
        PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY total) AS p50,
        PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY total) AS p75,
        AVG(total) AS promedio,
        MAX(total) AS maximo
    FROM casos_semanales
    GROUP BY semana_epi, enfermedad
)
SELECT
    s.semana_epi,
    s.enfermedad,
    ROUND(s.p25::NUMERIC, 1) AS zona_exito,
    ROUND(s.p50::NUMERIC, 1) AS zona_seguridad,
    ROUND(s.p75::NUMERIC, 1) AS zona_alerta,
    ROUND(s.promedio::NUMERIC, 1) AS promedio_historico,
    s.maximo AS maximo_historico,
    COALESCE(actual.total, 0) AS casos_actuales,
    EXTRACT(YEAR FROM CURRENT_DATE)::INT AS anio_actual,
    CASE
        WHEN COALESCE(actual.total, 0) <= s.p25 THEN 'exito'
        WHEN COALESCE(actual.total, 0) <= s.p50 THEN 'seguridad'
        WHEN COALESCE(actual.total, 0) <= s.p75 THEN 'alerta'
        ELSE 'epidemia'
    END AS clasificacion_canal
FROM stats s
LEFT JOIN casos_semanales actual
    ON actual.semana_epi = s.semana_epi
    AND actual.enfermedad = s.enfermedad
    AND actual.anio = EXTRACT(YEAR FROM CURRENT_DATE)::INT
ORDER BY s.enfermedad, s.semana_epi;

-- ============================================
-- 4. VISTA DE BITÁCORA (lectura simplificada)
-- ============================================

CREATE OR REPLACE VIEW public.v_bitacora_reciente AS
SELECT
    id_bitacora,
    tabla_afectada,
    operacion,
    id_registro,
    usuario_email,
    fecha,
    datos_anteriores,
    datos_nuevos
FROM public.bitacora_auditoria
ORDER BY fecha DESC
LIMIT 100;
